In [ ]:

import sys
import platform
import subprocess

print("Python version:", sys.version)
print("Platform:", platform.platform())
print("Architecture:", platform.machine())

subprocess.run([sys.executable, "-m", "pip", "--version"])
subprocess.run(["nvidia-smi"])

Python version: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Platform: Linux-6.6.122+-x86_64-with-glibc2.39
Architecture: x86_64

CompletedProcess(args=['nvidia-smi'], returncode=0)

In [ ]:

import sys
import subprocess

print("Python executable:", sys.executable)

result = subprocess.run(
    ["nvidia-smi"],
    capture_output=True,
    text=True
)

print("\nGPU information:")
print(result.stdout if result.returncode == 0 else result.stderr)

print("\nPip version:")
subprocess.run([sys.executable, "-m", "pip", "--version"])

Python executable: /usr/bin/python3

GPU information:
Fri Oct 16 06:05:56 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             15W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+


Pip version:

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', '--version'], returncode=0)

In [ ]:

import sys
import subprocess

result = subprocess.run(
    [sys.executable, "-m", "pip", "--version"],
    capture_output=True,
    text=True
)

print("Exit code:", result.returncode)
print(result.stdout)
print(result.stderr)

Exit code: 0
pip 24.1.2 from /usr/local/lib/python3.13/dist-packages/pip (python 3.13)

In [ ]:

import sys
import subprocess

command = [
    sys.executable, "-m", "pip",
    "index", "versions", "paddlepaddle-gpu",
    "-i", "https://www.paddlepaddle.org.cn/packages/stable/cu130/"
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True,
    timeout=120
)

print("Exit code:", result.returncode)
print(result.stdout)
print(result.stderr[-5000:])

Exit code: 0
paddlepaddle-gpu (3.4.0)
Available versions: 3.4.0, 3.3.1, 3.3.0, 3.2.2, 3.2.1

WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.

In [ ]:

import sys
import subprocess

command = [
    sys.executable, "-m", "pip", "install",
    "paddlepaddle-gpu==3.3.1",
    "-i", "https://www.paddlepaddle.org.cn/packages/stable/cu130/"
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True,
    timeout=600
)

print("Exit code:", result.returncode)
print(result.stdout[-5000:])
print(result.stderr[-5000:])

Exit code: 0
u==3.3.1) (13.0.85)
Collecting nvidia-cudnn-cu13==9.13.0.50 (from paddlepaddle-gpu==3.3.1)
  Downloading https://paddle-whl.cdn.bcebos.com/stable/cu130/nvidia-cudnn-cu13/nvidia_cudnn_cu13-9.13.0.50-py3-none-manylinux_2_27_x86_64.whl (348.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.6/348.6 MB 3.5 MB/s eta 0:00:00
Collecting nvidia-cublas==13.0.2.14 (from paddlepaddle-gpu==3.3.1)
  Downloading https://paddle-whl.cdn.bcebos.com/stable/cu130/nvidia-cublas/nvidia_cublas-13.0.2.14-py3-none-manylinux_2_27_x86_64.whl (420.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 420.9/420.9 MB 3.6 MB/s eta 0:00:00
Requirement already satisfied: nvidia-cufft==12.0.0.61 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (12.0.0.61)
Requirement already satisfied: nvidia-curand==10.4.0.35 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (12.6.3.3)
Collecting nvidia-cusparselt-cu13==0.8.1 (from paddlepaddle-gpu==3.3.1)
  Downloading https://paddle-whl.cdn.bcebos.com/stable/cu130/nvidia-cusparselt-cu13/nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 5.5 MB/s eta 0:00:00
Collecting nvidia-nccl-cu13==2.28.3 (from paddlepaddle-gpu==3.3.1)
  Downloading https://paddle-whl.cdn.bcebos.com/stable/cu130/nvidia-nccl-cu13/nvidia_nccl_cu13-2.28.3-py3-none-manylinux_2_18_x86_64.whl (195.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.3/195.3 MB 5.2 MB/s eta 0:00:00
Requirement already satisfied: nvidia-nvtx==13.0.85 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (13.0.85)
Requirement already satisfied: nvidia-nvjitlink==13.0.88 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (13.0.88)
Requirement already satisfied: nvidia-cufile==1.15.1.6 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (1.15.1.6)
Requirement already satisfied: cuda-python==13.0.3 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (13.0.3)
Requirement already satisfied: nvidia-cuda-cccl==13.0.85 in /usr/local/lib/python3.13/dist-packages (from paddlepaddle-gpu==3.3.1) (13.0.85)
Requirement already satisfied: cuda-bindings~=13.0.3 in /usr/local/lib/python3.13/dist-packages (from cuda-python==13.0.3->paddlepaddle-gpu==3.3.1) (13.0.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-python==13.0.3->paddlepaddle-gpu==3.3.1) (1.8.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx->paddlepaddle-gpu==3.3.1) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx->paddlepaddle-gpu==3.3.1) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx->paddlepaddle-gpu==3.3.1) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx->paddlepaddle-gpu==3.3.1) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx->paddlepaddle-gpu==3.3.1) (0.16.0)
Installing collected packages: nvidia-cusparselt-cu13, opt_einsum, nvidia-nccl-cu13, nvidia-cuda-runtime, nvidia-cublas, nvidia-cudnn-cu13, paddlepaddle-gpu
  Attempting uninstall: nvidia-cusparselt-cu13
    Found existing installation: nvidia-cusparselt-cu13 0.8.0
    Uninstalling nvidia-cusparselt-cu13-0.8.0:
      Successfully uninstalled nvidia-cusparselt-cu13-0.8.0
  Attempting uninstall: opt_einsum
    Found existing installation: opt_einsum 3.4.0
    Uninstalling opt_einsum-3.4.0:
      Successfully uninstalled opt_einsum-3.4.0
  Attempting uninstall: nvidia-nccl-cu13
    Found existing installation: nvidia-nccl-cu13 2.28.9
    Uninstalling nvidia-nccl-cu13-2.28.9:
      Successfully uninstalled nvidia-nccl-cu13-2.28.9
  Attempting uninstall: nvidia-cuda-runtime
    Found existing installation: nvidia-cuda-runtime 13.0.96
    Uninstalling nvidia-cuda-runtime-13.0.96:
      Successfully uninstalled nvidia-cuda-runtime-13.0.96
  Attempting uninstall: nvidia-cublas
    Found existing installation: nvidia-cublas 13.1.0.3
    Uninstalling nvidia-cublas-13.1.0.3:
      Successfully uninstalled nvidia-cublas-13.1.0.3
  Attempting uninstall: nvidia-cudnn-cu13
    Found existing installation: nvidia-cudnn-cu13 9.19.0.56
    Uninstalling nvidia-cudnn-cu13-9.19.0.56:
      Successfully uninstalled nvidia-cudnn-cu13-9.19.0.56
Successfully installed nvidia-cublas-13.0.2.14 nvidia-cuda-runtime-13.0.88 nvidia-cudnn-cu13-9.13.0.50 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.28.3 opt_einsum-3.3.0 paddlepaddle-gpu-3.3.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.11.0+cu130 requires nvidia-cudnn-cu13==9.19.0.56; platform_system == "Linux", but you have nvidia-cudnn-cu13 9.13.0.50 which is incompatible.
torch 2.11.0+cu130 requires nvidia-cusparselt-cu13==0.8.0; platform_system == "Linux", but you have nvidia-cusparselt-cu13 0.8.1 which is incompatible.
torch 2.11.0+cu130 requires nvidia-nccl-cu13==2.28.9; platform_system == "Linux", but you have nvidia-nccl-cu13 2.28.3 which is incompatible.

In [ ]:

import paddle

print("PaddlePaddle version:", paddle.__version__)
print("CUDA support:", paddle.is_compiled_with_cuda())
print("Active device:", paddle.device.get_device())

paddle.utils.run_check()

/usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)

PaddlePaddle version: 3.3.1
CUDA support: True
Active device: gpu:0
Running verify PaddlePaddle program ...

/usr/local/lib/python3.13/dist-packages/paddle/pir/math_op_patch.py:241: UserWarning: Tensor do not have 'place' interface for pir graph mode, try not to use it. None will be returned.
  warnings.warn(

PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

In [ ]:

import sys
import subprocess

result = subprocess.run(
    [
        sys.executable, "-m", "pip", "install",
        "paddleocr==3.7.0"
    ],
    capture_output=True,
    text=True,
    timeout=600
)

print("Exit code:", result.returncode)
print(result.stdout[-4000:])
print(result.stderr[-4000:])

Exit code: 0
lex[ocr-core]<3.8.0,>=3.7.0->paddleocr==3.7.0)
  Downloading crc32c-2.9.post0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=41->modelscope-hub>=0.4.6->modelscope>=1.28.0->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr==3.7.0) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=41->modelscope-hub>=0.4.6->modelscope>=1.28.0->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr==3.7.0) (3.0)
Downloading paddleocr-3.7.0-py3-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.8/146.8 kB 16.9 MB/s eta 0:00:00
Downloading paddlex-3.7.2-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 106.2 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (759 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 759.5/759.5 kB 61.9 MB/s eta 0:00:00
Downloading opencv_contrib_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 MB 11.4 MB/s eta 0:00:00
Downloading aistudio_sdk-0.3.9-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.2/67.2 kB 7.9 MB/s eta 0:00:00
Downloading modelscope-1.40.2-py3-none-any.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 124.1 MB/s eta 0:00:00
Downloading pypdfium2-5.14.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 100.1 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Downloading pyclipper-1.4.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (972 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 972.1/972.1 kB 53.3 MB/s eta 0:00:00
Downloading python_bidi-0.6.11-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.7/295.7 kB 16.3 MB/s eta 0:00:00
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 5.5 MB/s eta 0:00:00
Downloading ujson-6.0.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 6.7 MB/s eta 0:00:00
Downloading modelscope_hub-0.4.6-py3-none-any.whl (237 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.2/237.2 kB 16.7 MB/s eta 0:00:00
Downloading bce_python_sdk-0.9.79-py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.3/440.3 kB 24.8 MB/s eta 0:00:00
Downloading crc32c-2.9.post0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 7.0 MB/s eta 0:00:00
Downloading pycryptodome-4.0.0-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 52.0 MB/s eta 0:00:00
Installing collected packages: ujson, ruamel.yaml, PyYAML, python-bidi, pypdfium2, pycryptodome, pyclipper, opencv-contrib-python, crc32c, colorlog, bce-python-sdk, modelscope-hub, aistudio-sdk, modelscope, paddlex, paddleocr
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: opencv-contrib-python
    Found existing installation: opencv-contrib-python 4.14.0.94
    Uninstalling opencv-contrib-python-4.14.0.94:
      Successfully uninstalled opencv-contrib-python-4.14.0.94
Successfully installed PyYAML-6.0.2 aistudio-sdk-0.3.9 bce-python-sdk-0.9.79 colorlog-6.12.0 crc32c-2.9.post0 modelscope-1.40.2 modelscope-hub-0.4.6 opencv-contrib-python-4.10.0.84 paddleocr-3.7.0 paddlex-3.7.2 pyclipper-1.4.0 pycryptodome-4.0.0 pypdfium2-5.14.0 python-bidi-0.6.11 ruamel.yaml-0.19.1 ujson-6.0.0

In [ ]:

import traceback

try:
    from paddlex import create_pipeline
    print("PaddleX import successful")
except Exception:
    traceback.print_exc()

PaddleX import successful

In [ ]:

import sys
import subprocess

result = subprocess.run(
    [
        sys.executable,
        "-c",
        "from paddleocr import PaddleOCR; print('PaddleOCR import successful')"
    ],
    capture_output=True,
    text=True,
    timeout=120
)

print("Exit code:", result.returncode)
print("Output:")
print(result.stdout)
print("Error:")
print(result.stderr[-5000:])

Exit code: 0
Output:
PaddleOCR import successful

Error:

In [ ]:

import importlib.metadata as md
import os

for package in [
    "torch",
    "torchvision",
    "nvidia-nccl-cu11",
    "nvidia-nccl-cu12",
    "paddlepaddle-gpu",
    "paddleocr",
    "paddlex",
    "modelscope",
]:
    try:
        print(f"{package}: {md.version(package)}")
    except md.PackageNotFoundError:
        print(f"{package}: not installed")

print("\nLD_LIBRARY_PATH:")
print(os.environ.get("LD_LIBRARY_PATH", "(not set)"))

torch: 2.11.0+cu130
torchvision: 0.26.0+cu130
nvidia-nccl-cu11: not installed
nvidia-nccl-cu12: 2.32.3
paddlepaddle-gpu: 3.3.1
paddleocr: 3.7.0
paddlex: 3.7.2
modelscope: 1.40.2

LD_LIBRARY_PATH:
/usr/local/lib/python3.13/dist-packages/cv2/../../lib64:/usr/lib64-nvidia

In [ ]:

import sys
import subprocess

code = """
import torch
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("PyTorch CUDA version:", torch.version.cuda)
"""

result = subprocess.run(
    [sys.executable, "-c", code],
    capture_output=True,
    text=True,
    timeout=120
)

print("Exit code:", result.returncode)
print(result.stdout)
print(result.stderr[-4000:])

Exit code: 0
PyTorch: 2.11.0+cu130
CUDA available: True
PyTorch CUDA version: 13.0

In [ ]:

import os
import subprocess
import sys

torch_lib = (
    "/usr/local/lib/python3.13/dist-packages/"
    "torch/lib/libtorch_cuda.so"
)

print("Checking PyTorch CUDA library dependencies:\n")

result = subprocess.run(
    ["ldd", torch_lib],
    capture_output=True,
    text=True
)

for line in result.stdout.splitlines():
    if "nccl" in line.lower() or "not found" in line.lower():
        print(line)

print("\nSystem NCCL libraries:\n")

result = subprocess.run(
    ["bash", "-lc", "ldconfig -p | grep -i nccl"],
    capture_output=True,
    text=True
)

print(result.stdout or "No NCCL entries found in ldconfig.")

Checking PyTorch CUDA library dependencies:

	libnccl.so.2 => /usr/local/lib/python3.13/dist-packages/torch/lib/../../nvidia/nccl/lib/libnccl.so.2 (0x00007bd06b400000)

System NCCL libraries:

	libnccl.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnccl.so.2
	libnccl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnccl.so

In [ ]:

import os
import subprocess
from importlib.metadata import version, PackageNotFoundError

paths = [
    "/usr/local/lib/python3.13/dist-packages/nvidia/nccl/lib/libnccl.so.2",
    "/lib/x86_64-linux-gnu/libnccl.so.2",
]

for path in paths:
    print("\nLibrary:", path)
    print("Resolved path:", os.path.realpath(path))

    if not os.path.exists(path):
        print("File not found")
        continue

    result = subprocess.run(
        ["nm", "-D", path],
        capture_output=True,
        text=True
    )

    matches = [
        line for line in result.stdout.splitlines()
        if "ncclCommWindowDeregister" in line
    ]

    print(
        "Symbol found:" if matches else "Symbol NOT found:",
        matches if matches else ""
    )

for package in ["nvidia-nccl-cu13", "nvidia-nccl-cu12", "nvidia-nccl-cu11"]:
    try:
        print(f"{package}: {version(package)}")
    except PackageNotFoundError:
        print(f"{package}: not installed")

Library: /usr/local/lib/python3.13/dist-packages/nvidia/nccl/lib/libnccl.so.2
Resolved path: /usr/local/lib/python3.13/dist-packages/nvidia/nccl/lib/libnccl.so.2
Symbol found: ['00000000000a4520 W ncclCommWindowDeregister', '00000000000a4520 T pncclCommWindowDeregister']

Library: /lib/x86_64-linux-gnu/libnccl.so.2
Resolved path: /usr/lib/x86_64-linux-gnu/libnccl.so.2.28.3
Symbol found: ['00000000000b1860 W ncclCommWindowDeregister', '00000000000b1860 T pncclCommWindowDeregister']
nvidia-nccl-cu13: 2.28.3
nvidia-nccl-cu12: 2.32.3
nvidia-nccl-cu11: not installed

In [ ]:

import os
import subprocess
import sys

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

result = subprocess.run(
    [
        sys.executable,
        "-c",
        """
import torch
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("PyTorch CUDA version:", torch.version.cuda)
"""
    ],
    env=env,
    capture_output=True,
    text=True,
    timeout=120
)

print("Exit code:", result.returncode)
print("Output:\n", result.stdout)
print("Error:\n", result.stderr[-3000:])

Exit code: 0
Output:
 PyTorch: 2.11.0+cu130
CUDA available: True
PyTorch CUDA version: 13.0

Error:

In [ ]:

import os
import subprocess
import sys

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

code = """
import paddle
print("PaddlePaddle:", paddle.__version__)
print("Paddle GPU:", paddle.is_compiled_with_cuda())

from paddleocr import PaddleOCR
print("PaddleOCR import successful!")
"""

result = subprocess.run(
    [sys.executable, "-c", code],
    env=env,
    capture_output=True,
    text=True,
    timeout=180
)

print("Exit code:", result.returncode)
print("Output:\n", result.stdout)
print("Error:\n", result.stderr[-4000:])

Exit code: 0
Output:
 PaddlePaddle: 3.3.1
Paddle GPU: True
PaddleOCR import successful!

Error:
 /usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)

In [ ]:

import os
import subprocess
import sys

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

code = """
from paddleocr import PaddleOCR

ocr = PaddleOCR(
    lang="en",
    ocr_version="PP-OCRv5",
    device="gpu:0",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

print("PaddleOCR model initialized successfully!")
"""

result = subprocess.run(
    [sys.executable, "-c", code],
    env=env,
    capture_output=True,
    text=True,
    timeout=300
)

print("Exit code:", result.returncode)
print("Output:\\n", result.stdout[-5000:])
print("Error:\\n", result.stderr[-5000:])

Exit code: 0
Output:\n PaddleOCR model initialized successfully!

Error:\n Creating model: ('PP-OCRv5_server_det', None, None)
Checking connectivity to the model hosters, this may take a while. To bypass this check, set `PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK` to `True`.
Using official model (PP-OCRv5_server_det), the model files will be automatically downloaded and saved in `/root/.paddlex/official_models/PP-OCRv5_server_det`.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]
Fetching 6 files:  17%|█▋        | 1/6 [00:00<00:01,  3.82it/s]
Fetching 6 files:  67%|██████▋   | 4/6 [00:00<00:00, 12.81it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:02<00:00,  2.38it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:02<00:00,  2.86it/s]
/usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('en_PP-OCRv5_mobile_rec', None, None)
Using official model (en_PP-OCRv5_mobile_rec), the model files will be automatically downloaded and saved in `/root/.paddlex/official_models/en_PP-OCRv5_mobile_rec`.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]
Fetching 6 files:  17%|█▋        | 1/6 [00:00<00:01,  3.79it/s]
Fetching 6 files:  50%|█████     | 3/6 [00:00<00:00,  9.03it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:01<00:00,  3.83it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:01<00:00,  4.14it/s]

In [ ]:

import os

dataset_path = "/content/seven-segment-ocr"
ground_truth_path = os.path.join(
    dataset_path, "data", "ocr_training_data", "gt.txt"
)

print("Dataset folder exists:", os.path.isdir(dataset_path))
print("Ground-truth file exists:", os.path.isfile(ground_truth_path))

if os.path.isfile(ground_truth_path):
    with open(ground_truth_path, "r", encoding="utf-8") as f:
        print("\nFirst 5 label lines:")
        for _, line in zip(range(5), f):
            print(line.rstrip())

Dataset folder exists: False
Ground-truth file exists: False

In [ ]:
!git clone https://github.com/renjithsasidharan/seven-segment-ocr.git /content/seven-segment-ocr

Cloning into '/content/seven-segment-ocr'...
remote: Enumerating objects: 1021, done.
remote: Total 1021 (delta 0), reused 0 (delta 0), pack-reused 1021 (from 1)
Receiving objects: 100% (1021/1021), 281.11 MiB | 18.75 MiB/s, done.
Resolving deltas: 100% (41/41), done.

In [ ]:

import os

dataset_path = "/content/seven-segment-ocr"

for root, dirs, files in os.walk(dataset_path):
    dirs[:] = [d for d in dirs if d not in [".git"]]

    level = root.replace(dataset_path, "").count(os.sep)
    if level > 3:
        dirs[:] = []
        continue

    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for filename in files[:8]:
        print(f"{indent}  {filename}")

    if len(files) > 8:
        print(f"{indent}  ... and {len(files) - 8} more files")

seven-segment-ocr/
  predict.py
  .gitignore
  model_float16.tflite
  eval_tflite.py
  README.md
  keras_ocr_7_seg.ipynb
  create_ocr_training_data_from_annotations.py
  requirements.txt
  test/
    2.png
    1.png
  data/
    annotations/
      Label.txt
      fileState.txt
      23122019DAE01QMR100016077.jpeg
      Cache.cach
      23122019DAE01QMR100012657.jpeg
    ocr_training_data/
      d71d0863-5bad-416b-bbe6-906c828aefff.png
      4a233545-0904-4c94-9403-b2162161739f.png
      5000aa5a-d888-410a-91ba-72493406ccfc.png
      7140aea1-ddb6-42ff-a172-52b79200f08a.png
      185b8fb4-4821-44c0-b092-832545376398.png
      0bc0a94a-65c3-4734-8e4b-c14a4852e244.png
      d436e50d-55da-4fbc-9c17-eacb5306c2fe.png
      a1b31313-2602-47ce-8a85-554b6740a885.png
      ... and 312 more files
  results/
    1.jpg
    3.jpg
    annotations.jpg
    6.jpg
    cm.jpg
    2.jpg
    4.jpg
    5.jpg

In [ ]:

import os

base = "/content/seven-segment-ocr"

gt_path = os.path.join(base, "data", "ocr_training_data", "gt.txt")
annotation_path = os.path.join(base, "data", "annotations", "Label.txt")

for path in [gt_path, annotation_path]:
    print("\nFile:", path)
    print("Exists:", os.path.isfile(path))

    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            for i, line in zip(range(5), f):
                print(repr(line.rstrip()))

File: /content/seven-segment-ocr/data/ocr_training_data/gt.txt
Exists: True
'6c5bec3e-68aa-4794-bff1-116e7db7ae0c.png\t009926'
'e316bb27-82fa-4382-920d-c69f2389d55a.png\t012240'
'6ae95c80-c0c5-4a1f-8826-07f4b93caa27.png\t000851'
'c8ee3e63-de17-4b67-bce2-ee7731696f0f.png\t24571'
'98ce7c68-fb7c-4601-8133-0fdacea3f9c1.png\t004824.0'

File: /content/seven-segment-ocr/data/annotations/Label.txt
Exists: True
'annotations/23122019DAE01QMR100012657.jpeg\t[{"transcription": "003257", "points": [[81, 25], [211, 25], [211, 67], [81, 67]], "difficult": false}]'
'annotations/23122019DAE01QMR100016077.jpeg\t[{"transcription": "004344.9", "points": [[110, 35], [241, 35], [241, 77], [110, 77]], "difficult": false}]'

In [ ]:

import os

base = "/content/seven-segment-ocr"
gt_path = os.path.join(base, "data", "ocr_training_data", "gt.txt")
annotation_path = os.path.join(base, "data", "annotations", "Label.txt")

with open(gt_path, "r", encoding="utf-8") as f:
    gt_lines = [line.strip() for line in f if line.strip()]

with open(annotation_path, "r", encoding="utf-8") as f:
    annotation_lines = [line.strip() for line in f if line.strip()]

print("Cropped-image labels:", len(gt_lines))
print("Annotated original images:", len(annotation_lines))

print("\nFirst cropped-image label:")
print(gt_lines[0])

print("\nFirst original-image annotation:")
print(annotation_lines[0])

Cropped-image labels: 319
Annotated original images: 2

First cropped-image label:
6c5bec3e-68aa-4794-bff1-116e7db7ae0c.png	009926

First original-image annotation:
annotations/23122019DAE01QMR100012657.jpeg	[{"transcription": "003257", "points": [[81, 25], [211, 25], [211, 67], [81, 67]], "difficult": false}]

In [ ]:

import os
import subprocess
import sys

base = "/content/seven-segment-ocr"
gt_path = os.path.join(base, "data", "ocr_training_data", "gt.txt")

with open(gt_path, "r", encoding="utf-8") as f:
    first_line = f.readline().strip()

image_name, true_text = first_line.split("\t", 1)
image_path = os.path.join(base, "data", "ocr_training_data", image_name)

print("Image:", image_name)
print("Ground-truth text:", true_text)
print("Image exists:", os.path.isfile(image_path))

Image: 6c5bec3e-68aa-4794-bff1-116e7db7ae0c.png
Ground-truth text: 009926
Image exists: True

In [ ]:

import os
import subprocess
import sys

base = "/content/seven-segment-ocr"
gt_path = os.path.join(base, "data", "ocr_training_data", "gt.txt")

with open(gt_path, "r", encoding="utf-8") as f:
    image_name, true_text = f.readline().strip().split("\t", 1)

image_path = os.path.join(base, "data", "ocr_training_data", image_name)

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

code = """
import sys
from paddleocr import PaddleOCR

image_path = sys.argv[1]

ocr = PaddleOCR(
    lang="en",
    ocr_version="PP-OCRv5",
    device="gpu:0",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

results = ocr.predict(image_path)

for result in results:
    print("OCR result:")
    print(result)
"""

result = subprocess.run(
    [sys.executable, "-c", code, image_path],
    env=env,
    capture_output=True,
    text=True,
    timeout=300
)

print("Ground truth:", true_text)
print("Exit code:", result.returncode)
print("\nOutput:\n", result.stdout[-5000:])
print("\nError:\n", result.stderr[-3000:])

Ground truth: 009926
Exit code: 0

Output:
 OCR result:
{'input_path': '/content/seven-segment-ocr/data/ocr_training_data/6c5bec3e-68aa-4794-bff1-116e7db7ae0c.png', 'page_index': None, 'doc_preprocessor_res': {'output_img': array([[[209, ..., 218],
        ...,
        [117, ..., 250]],

       ...,

       [[149, ..., 205],
        ...,
        [ 88, ..., 197]]], dtype=uint8)}, 'dt_polys': [array([[ 4,  0],
       ...,
       [ 4, 31]], dtype=int16)], 'model_settings': {'use_doc_preprocessor': False, 'use_textline_orientation': False}, 'text_det_params': {'limit_side_len': 64, 'limit_type': 'min', 'thresh': 0.3, 'max_side_limit': 4000, 'box_thresh': 0.6, 'unclip_ratio': 1.5}, 'text_type': 'general', 'text_rec_score_thresh': 0.0, 'return_word_box': False, 'rec_texts': ['009926'], 'rec_scores': [0.9994458556175232], 'rec_polys': [array([[ 4,  0],
       ...,
       [ 4, 31]], dtype=int16)], 'vis_fonts': [<paddlex.utils.fonts.Font object at 0x7ecf75db0b90>], 'textline_orientation_angles': [-1], 'rec_boxes': array([[ 4, ..., 31]], dtype=int16)}


Error:
 Creating model: ('PP-OCRv5_server_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
/usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('en_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/en_PP-OCRv5_mobile_rec`.

In [ ]:

import os
import pandas as pd
from sklearn.model_selection import train_test_split

dataset_dir = "/content/seven-segment-ocr/data/ocr_training_data"
gt_path = os.path.join(dataset_dir, "gt.txt")

# Read image filenames and their correct text labels
df = pd.read_csv(
    gt_path,
    sep="\t",
    header=None,
    names=["image", "text"],
    dtype=str
)

# Keep only records whose image files exist
df["image_path"] = df["image"].apply(
    lambda name: os.path.join(dataset_dir, name)
)
df = df[df["image_path"].apply(os.path.isfile)].reset_index(drop=True)

# 70% train, 30% temporary
train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=42,
    shuffle=True
)

# Split the remaining 30% equally into validation and test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    shuffle=True
)

print("Total images:", len(df))
print("Training images:", len(train_df))
print("Validation images:", len(val_df))
print("Test images:", len(test_df))

print("\nSample test records:")
print(test_df[["image", "text"]].head())

Total images: 319
Training images: 223
Validation images: 48
Test images: 48

Sample test records:
                                        image     text
155  5b16bbad-b02c-435c-8840-693a452a7dcb.png   1179.6
145  e737682e-5d38-4848-b2d8-c28489f3f8fd.png  0018041
239  2658364a-6792-4a83-af6f-fd94ca925e68.png  01441.8
265  557de184-820b-4a29-8d3c-987c73759635.png   1927.7
260  ff91b07b-cf94-49fa-9f43-0000c9d9b031.png    672.7

In [ ]:

import os
import subprocess
import sys
import pandas as pd

# Save the fixed test set for the separate Python process
input_csv = "/content/ppocr_test_inputs.csv"
output_csv = "/content/ppocr_test_results.csv"

test_inputs = test_df[["image", "text", "image_path"]].copy()
test_inputs.to_csv(input_csv, index=False)

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

code = r'''
import os
import time
import pandas as pd
import paddle
from paddleocr import PaddleOCR

input_csv = "/content/ppocr_test_inputs.csv"
output_csv = "/content/ppocr_test_results.csv"

df = pd.read_csv(input_csv, dtype=str)

ocr = PaddleOCR(
    lang="en",
    ocr_version="PP-OCRv5",
    device="gpu:0",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

# Warm up the model before measuring latency
ocr.predict(df.iloc[0]["image_path"])

rows = []

for i, row in df.iterrows():
    image_path = row["image_path"]

    # Synchronize GPU before and after timing inference
    paddle.device.cuda.synchronize()
    start = time.perf_counter()

    results = ocr.predict(image_path)

    paddle.device.cuda.synchronize()
    latency_ms = (time.perf_counter() - start) * 1000

    predicted_text = ""
    confidence = None

    if results:
        result = results[0]
        texts = result.get("rec_texts", [])
        scores = result.get("rec_scores", [])

        predicted_text = "".join(str(t) for t in texts)
        if scores:
            confidence = float(scores[0])

    rows.append({
        "image": row["image"],
        "ground_truth": row["text"],
        "prediction": predicted_text,
        "confidence": confidence,
        "latency_ms": latency_ms,
    })

    print(f"Processed {i + 1}/{len(df)}", flush=True)

pd.DataFrame(rows).to_csv(output_csv, index=False)
print("\\nSaved results:", output_csv)
print("Rows saved:", len(rows))
'''

result = subprocess.run(
    [sys.executable, "-c", code],
    env=env,
    capture_output=True,
    text=True,
    timeout=1800
)

print("Exit code:", result.returncode)
print("\nOutput:\n", result.stdout[-5000:])
print("\nErrors:\n", result.stderr[-3000:])

if result.returncode == 0 and os.path.isfile(output_csv):
    results_df = pd.read_csv(output_csv, dtype={"ground_truth": str,
                                                "prediction": str})
    print("\nResults shape:", results_df.shape)
    print(results_df.head())
else:
    print("\nThe evaluation did not finish successfully. Please share the error.")

Exit code: 0

Output:
 Processed 1/48
Processed 2/48
Processed 3/48
Processed 4/48
Processed 5/48
Processed 6/48
Processed 7/48
Processed 8/48
Processed 9/48
Processed 10/48
Processed 11/48
Processed 12/48
Processed 13/48
Processed 14/48
Processed 15/48
Processed 16/48
Processed 17/48
Processed 18/48
Processed 19/48
Processed 20/48
Processed 21/48
Processed 22/48
Processed 23/48
Processed 24/48
Processed 25/48
Processed 26/48
Processed 27/48
Processed 28/48
Processed 29/48
Processed 30/48
Processed 31/48
Processed 32/48
Processed 33/48
Processed 34/48
Processed 35/48
Processed 36/48
Processed 37/48
Processed 38/48
Processed 39/48
Processed 40/48
Processed 41/48
Processed 42/48
Processed 43/48
Processed 44/48
Processed 45/48
Processed 46/48
Processed 47/48
Processed 48/48
\nSaved results: /content/ppocr_test_results.csv
Rows saved: 48


Errors:
 /usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-OCRv5_server_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('en_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/en_PP-OCRv5_mobile_rec`.
<string>:31: VisibleDeprecationWarning:
Warning:
API "paddle.device.cuda.synchronize" is deprecated since 2.5.0, and will be removed in future versions. Please use "paddle.device.synchronize" instead.
    Reason: synchronize in paddle.device.cuda will be removed in future
<string>:36: VisibleDeprecationWarning:
Warning:
API "paddle.device.cuda.synchronize" is deprecated since 2.5.0, and will be removed in future versions. Please use "paddle.device.synchronize" instead.
    Reason: synchronize in paddle.device.cuda will be removed in future


Results shape: (48, 5)
                                      image ground_truth prediction  \
0  5b16bbad-b02c-435c-8840-693a452a7dcb.png       1179.6     1179.6
1  e737682e-5d38-4848-b2d8-c28489f3f8fd.png      0018041     1804 1
2  2658364a-6792-4a83-af6f-fd94ca925e68.png      01441.8    1418kWh
3  557de184-820b-4a29-8d3c-987c73759635.png       1927.7     1427.7
4  ff91b07b-cf94-49fa-9f43-0000c9d9b031.png        672.7      672.7

   confidence  latency_ms
0    0.966358   41.516204
1    0.984002   39.458459
2    0.985317   62.092333
3    0.863855   51.823531
4    0.984621   40.378397

In [ ]:
%pip install jiwer

Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.13/dist-packages (from jiwer) (8.5.0)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 93.1 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.6

In [ ]:

import pandas as pd
import numpy as np
import re

from jiwer import cer, wer

results_path = "/content/ppocr_test_results.csv"
results_df = pd.read_csv(
    results_path,
    dtype={"ground_truth": str, "prediction": str}
).fillna("")

def normalize_text(text):
    # Remove whitespace and common unit text, preserving digits and decimals
    text = str(text).strip().replace(" ", "")
    text = re.sub(r"(?i)kwh", "", text)
    return text

y_true = results_df["ground_truth"].map(normalize_text).tolist()
y_pred = results_df["prediction"].map(normalize_text).tolist()

# Accuracy and error metrics
exact_matches = sum(a == b for a, b in zip(y_true, y_pred))
exact_match_accuracy = exact_matches / len(y_true) * 100
cer_value = cer(y_true, y_pred) * 100
wer_value = wer(y_true, y_pred) * 100

# Latency metrics (milliseconds)
latencies = results_df["latency_ms"].astype(float)

print("===== PP-OCR TEST RESULTS =====")
print("Test images:", len(results_df))
print(f"Exact matches: {exact_matches}/{len(results_df)}")
print(f"Exact-match accuracy: {exact_match_accuracy:.2f}%")
print(f"CER: {cer_value:.2f}%")
print(f"WER: {wer_value:.2f}%")
print(f"Mean latency: {latencies.mean():.2f} ms")
print(f"P50 latency: {latencies.quantile(0.50):.2f} ms")
print(f"P99 latency: {latencies.quantile(0.99):.2f} ms")

print("\n===== INCORRECT PREDICTIONS =====")
errors = results_df[
    results_df.apply(
        lambda row: normalize_text(row["ground_truth"])
        != normalize_text(row["prediction"]),
        axis=1
    )
]
print(errors[["image", "ground_truth", "prediction"]].to_string(index=False))

results_df.to_csv("/content/ppocr_test_results.csv", index=False)

===== PP-OCR TEST RESULTS =====
Test images: 48
Exact matches: 11/48
Exact-match accuracy: 22.92%
CER: 46.48%
WER: 77.08%
Mean latency: 31.98 ms
P50 latency: 29.88 ms
P99 latency: 59.61 ms

===== INCORRECT PREDICTIONS =====
                                   image ground_truth    prediction
e737682e-5d38-4848-b2d8-c28489f3f8fd.png      0018041        1804 1
2658364a-6792-4a83-af6f-fd94ca925e68.png      01441.8       1418kWh
557de184-820b-4a29-8d3c-987c73759635.png       1927.7        1427.7
29dd0121-4fb5-4733-b2c0-284a2fd5fc58.png       000001         0000O
ea18c8c2-2ad1-4c41-aede-ba4466608328.png       1025.0
37a62422-30df-45d9-a40c-a734b24cf312.png       1320.5         13205
b37eba6d-a5be-4317-ac73-ddf71fbe32cd.png        01404
4a6ad475-b76d-4cbb-8521-7461942453aa.png       7038.2  7038.2CUMkWh
60398bbe-4429-4bdb-921e-e113d87d0916.png       002163         00253
6adf68ae-f886-4586-a98f-cd7bcbb23e54.png      01442.1
9f3949ec-d8fa-4979-84b2-088209844b62.png       005228
4596bb11-3c38-42e5-bd11-59961bc223a9.png        10735
d436e50d-55da-4fbc-9c17-eacb5306c2fe.png       015738
78ff8f7c-13e8-48ed-9031-ca1cd7998bda.png       1643.2         16432
959591ae-bdd2-47e5-a05f-1a9e1b7e340c.png       3193.5        3 1935
7925f409-e735-45e1-a3d6-e2f160ba84e5.png          102
698d6380-94b5-4e31-8a2e-2fdb6f5034c5.png       1922.8         19228
dcd03294-f69c-4058-bacb-a6b2aa8e93d6.png         3879
4c25a941-9c43-4672-abc4-42f368768432.png       005407
ee93eb75-95a3-48f9-ac9d-37bb601ddf4d.png         82.7
d61232df-40a5-496f-8e92-e9a40fb17439.png     000542.8       0005428
c8ee3e63-de17-4b67-bce2-ee7731696f0f.png        24571
d601bdad-feda-4d62-a45c-72cdb4a6941a.png       1922.8
a1668c14-613f-44ce-b094-1ff96751b80a.png       009775
4a5ce403-9a68-482e-a18c-281e11e578a8.png       009239
0a4c38a6-fd25-4711-8eac-149d30f52ecc.png       9845.9         98459
3c9f625c-32e2-466a-8995-434247ff3238.png     000006.0     00 00068,
9592d6d1-e2c0-4d76-9c1f-27bf4daa83a0.png       012594
bb0a6b7f-0214-417a-abe8-ace45b078bf5.png       003398        003396
16c52a8a-379f-4fc2-8d15-de5eae5b865a.png     002932.4       J029324
091718eb-be08-48df-ade3-8f96e7d5a723.png     002240.2       0022402
2348d29f-1e5c-4a6c-ba0f-08a8b86ea6b6.png       020589
7ecf0a0a-7bc0-4e8f-bc8f-c5510674e1e6.png      01974.6     019746kW/
49ca379c-d22b-4ffe-8209-6c646c74860a.png         2609          2604
a5db5ea3-9476-409d-a8d1-7b757bede49c.png       4540.9 4540.9TTRALWh
dc012f1d-d5ef-4024-b050-c55bd94ac4d0.png         1241
9d5c34e8-051f-4f77-aa5d-6140f793d8ef.png         1740

In [ ]:

from PIL import Image
import os
import pandas as pd

dataset_dir = "/content/seven-segment-ocr/data/ocr_training_data"

results_df = pd.read_csv(
    "/content/ppocr_test_results.csv",
    dtype=str
).fillna("")

sample_images = results_df["image"].head(5).tolist()

print("Sample image dimensions:")
for filename in sample_images:
    path = os.path.join(dataset_dir, filename)
    with Image.open(path) as img:
        print(filename, "->", img.size, "| mode:", img.mode)

widths = []
heights = []

for filename in results_df["image"]:
    path = os.path.join(dataset_dir, filename)
    with Image.open(path) as img:
        width, height = img.size
        widths.append(width)
        heights.append(height)

print("\nDataset dimension summary:")
print("Minimum width:", min(widths))
print("Maximum width:", max(widths))
print("Minimum height:", min(heights))
print("Maximum height:", max(heights))

Sample image dimensions:
5b16bbad-b02c-435c-8840-693a452a7dcb.png -> (200, 31) | mode: RGB
e737682e-5d38-4848-b2d8-c28489f3f8fd.png -> (200, 31) | mode: RGB
2658364a-6792-4a83-af6f-fd94ca925e68.png -> (200, 31) | mode: RGB
557de184-820b-4a29-8d3c-987c73759635.png -> (200, 31) | mode: RGB
ff91b07b-cf94-49fa-9f43-0000c9d9b031.png -> (200, 31) | mode: RGB

Dataset dimension summary:
Minimum width: 200
Maximum width: 200
Minimum height: 31
Maximum height: 31

In [ ]:

import os
import subprocess
import sys

input_csv = "/content/ppocr_test_inputs.csv"
output_csv = "/content/ppocr_resized_test_results.csv"

env = os.environ.copy()
env["LD_PRELOAD"] = "/lib/x86_64-linux-gnu/libnccl.so.2"

code = r'''
import os
import time
import tempfile
import pandas as pd
import paddle
from PIL import Image
from paddleocr import PaddleOCR

df = pd.read_csv("/content/ppocr_test_inputs.csv", dtype=str)

ocr = PaddleOCR(
    lang="en",
    ocr_version="PP-OCRv5",
    device="gpu:0",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

rows = []

with tempfile.TemporaryDirectory() as temp_dir:
    # Warm-up with the first resized image
    first = Image.open(df.iloc[0]["image_path"]).convert("RGB")
    first = first.resize((800, 124), Image.Resampling.LANCZOS)
    first_path = os.path.join(temp_dir, "warmup.png")
    first.save(first_path)
    ocr.predict(first_path)

    for i, row in df.iterrows():
        image = Image.open(row["image_path"]).convert("RGB")
        image = image.resize((800, 124), Image.Resampling.LANCZOS)

        resized_path = os.path.join(temp_dir, f"image_{i}.png")
        image.save(resized_path)

        paddle.device.synchronize()
        start = time.perf_counter()
        results = ocr.predict(resized_path)
        paddle.device.synchronize()

        latency_ms = (time.perf_counter() - start) * 1000

        prediction = ""
        confidence = None

        if results:
            result = results[0]
            texts = result.get("rec_texts", [])
            scores = result.get("rec_scores", [])
            prediction = "".join(str(t) for t in texts)
            if scores:
                confidence = float(scores[0])

        rows.append({
            "image": row["image"],
            "ground_truth": row["text"],
            "prediction": prediction,
            "confidence": confidence,
            "latency_ms": latency_ms,
        })

        print(f"Processed {i + 1}/{len(df)}", flush=True)

pd.DataFrame(rows).to_csv(
    "/content/ppocr_resized_test_results.csv", index=False
)
print("Saved resized results:", len(rows))
'''

result = subprocess.run(
    [sys.executable, "-c", code],
    env=env,
    capture_output=True,
    text=True,
    timeout=1800
)

print("Exit code:", result.returncode)
print("Output:\n", result.stdout[-4000:])
print("Errors:\n", result.stderr[-2000:])

Exit code: 0
Output:
 Processed 1/48
Processed 2/48
Processed 3/48
Processed 4/48
Processed 5/48
Processed 6/48
Processed 7/48
Processed 8/48
Processed 9/48
Processed 10/48
Processed 11/48
Processed 12/48
Processed 13/48
Processed 14/48
Processed 15/48
Processed 16/48
Processed 17/48
Processed 18/48
Processed 19/48
Processed 20/48
Processed 21/48
Processed 22/48
Processed 23/48
Processed 24/48
Processed 25/48
Processed 26/48
Processed 27/48
Processed 28/48
Processed 29/48
Processed 30/48
Processed 31/48
Processed 32/48
Processed 33/48
Processed 34/48
Processed 35/48
Processed 36/48
Processed 37/48
Processed 38/48
Processed 39/48
Processed 40/48
Processed 41/48
Processed 42/48
Processed 43/48
Processed 44/48
Processed 45/48
Processed 46/48
Processed 47/48
Processed 48/48
Saved resized results: 48

Errors:
 /usr/local/lib/python3.13/dist-packages/paddle/utils/cpp_extension/extension_utils.py:712: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-OCRv5_server_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('en_PP-OCRv5_mobile_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/en_PP-OCRv5_mobile_rec`.

In [ ]:

import pandas as pd
import re
from jiwer import cer, wer

# Load both experiment results
baseline = pd.read_csv("/content/ppocr_test_results.csv")
resized = pd.read_csv("/content/ppocr_resized_test_results.csv")

# Use identical text normalization for a fair comparison
def normalize_text(text):
    text = str(text).strip().replace(" ", "")
    text = re.sub(r"(?i)kwh", "", text)
    return text

def calculate_metrics(df, experiment_name):
    actual = df["ground_truth"].map(normalize_text).tolist()
    predicted = df["prediction"].fillna("").map(normalize_text).tolist()

    exact_matches = sum(a == p for a, p in zip(actual, predicted))

    return {
        "Experiment": experiment_name,
        "Exact Matches": f"{exact_matches}/{len(df)}",
        "Exact Accuracy (%)": round(100 * exact_matches / len(df), 2),
        "CER (%)": round(cer(actual, predicted) * 100, 2),
        "WER (%)": round(wer(actual, predicted) * 100, 2),
        "Mean Latency (ms)": round(df["latency_ms"].mean(), 2),
        "P50 Latency (ms)": round(df["latency_ms"].quantile(0.50), 2),
        "P99 Latency (ms)": round(df["latency_ms"].quantile(0.99), 2),
        "Empty Predictions": int(
            df["prediction"].fillna("").str.strip().eq("").sum()
        )
    }

comparison = pd.DataFrame([
    calculate_metrics(baseline, "Original 200x31"),
    calculate_metrics(resized, "Resized 800x124")
])

print("PP-OCR BASELINE vs RESIZED IMAGE COMPARISON")
display(comparison)

PP-OCR BASELINE vs RESIZED IMAGE COMPARISON

,Experiment,Exact Matches,Exact Accuracy (%),CER (%),WER (%),Mean Latency (ms),P50 Latency (ms),P99 Latency (ms),Empty Predictions
0,Original 200x31,4/48,8.33,66.9,91.67,31.98,29.88,59.61,18
1,Resized 800x124,0/48,0.00,74.3,100.00,52.06,47.27,178.74,22

In [ ]:

import pandas as pd

baseline = pd.read_csv("/content/ppocr_test_results.csv")
resized = pd.read_csv("/content/ppocr_resized_test_results.csv")

print("BASELINE FILE ROWS:", len(baseline))
print("RESIZED FILE ROWS:", len(resized))

print("\nBASELINE SAMPLE")
display(baseline[["image", "ground_truth", "prediction"]].head(10))

print("\nRESIZED SAMPLE")
display(resized[["image", "ground_truth", "prediction"]].head(10))

BASELINE FILE ROWS: 48
RESIZED FILE ROWS: 48

BASELINE SAMPLE

                                      image  ground_truth prediction
0  5b16bbad-b02c-435c-8840-693a452a7dcb.png        1179.6     1179.6
1  e737682e-5d38-4848-b2d8-c28489f3f8fd.png       18041.0     1804 1
2  2658364a-6792-4a83-af6f-fd94ca925e68.png        1441.8    1418kWh
3  557de184-820b-4a29-8d3c-987c73759635.png        1927.7     1427.7
4  ff91b07b-cf94-49fa-9f43-0000c9d9b031.png         672.7      672.7
5  29dd0121-4fb5-4733-b2c0-284a2fd5fc58.png           1.0      0000O
6  ea18c8c2-2ad1-4c41-aede-ba4466608328.png        1025.0        NaN
7  37a62422-30df-45d9-a40c-a734b24cf312.png        1320.5      13205
8  b37eba6d-a5be-4317-ac73-ddf71fbe32cd.png        1404.0        NaN
9  502eda12-9c88-4801-88ac-eeee2cbfb9e0.png        2090.3   002090.3

RESIZED SAMPLE

                                      image  ground_truth prediction
0  5b16bbad-b02c-435c-8840-693a452a7dcb.png        1179.6        NaN
1  e737682e-5d38-4848-b2d8-c28489f3f8fd.png       18041.0     001804
2  2658364a-6792-4a83-af6f-fd94ca925e68.png        1441.8    81614MM
3  557de184-820b-4a29-8d3c-987c73759635.png        1927.7        NaN
4  ff91b07b-cf94-49fa-9f43-0000c9d9b031.png         672.7       672K
5  29dd0121-4fb5-4733-b2c0-284a2fd5fc58.png           1.0       1000
6  ea18c8c2-2ad1-4c41-aede-ba4466608328.png        1025.0        NaN
7  37a62422-30df-45d9-a40c-a734b24cf312.png        1320.5       3205
8  b37eba6d-a5be-4317-ac73-ddf71fbe32cd.png        1404.0        NaN
9  502eda12-9c88-4801-88ac-eeee2cbfb9e0.png        2090.3    0020903

DB+PP RESULTS-THE END

In [ ]:

import pandas as pd
import re
from jiwer import cer, wer

baseline = pd.read_csv(
    "/content/ppocr_test_results.csv",
    dtype=str,
    keep_default_na=False
)

resized = pd.read_csv(
    "/content/ppocr_resized_test_results.csv",
    dtype=str,
    keep_default_na=False
)

def normalize_text(text):
    text = str(text).strip().replace(" ", "")
    text = re.sub(r"(?i)kwh", "", text)
    return text

def calculate_metrics(df, name):
    actual = df["ground_truth"].map(normalize_text).tolist()
    predicted = df["prediction"].map(normalize_text).tolist()

    matches = sum(a == p for a, p in zip(actual, predicted))

    latencies = pd.to_numeric(df["latency_ms"], errors="coerce")

    return {
        "Experiment": name,
        "Exact Matches": f"{matches}/{len(df)}",
        "Exact Accuracy (%)": round(matches / len(df) * 100, 2),
        "CER (%)": round(cer(actual, predicted) * 100, 2),
        "WER (%)": round(wer(actual, predicted) * 100, 2),
        "Mean Latency (ms)": round(latencies.mean(), 2),
        "P50 Latency (ms)": round(latencies.quantile(0.50), 2),
        "P99 Latency (ms)": round(latencies.quantile(0.99), 2),
        "Empty Predictions": sum(p.strip() == "" for p in predicted)
    }

display(pd.DataFrame([
    calculate_metrics(baseline, "Original 200x31"),
    calculate_metrics(resized, "Resized 800x124")
]))

print("\nGround-truth formatting check:")
print(baseline[["ground_truth", "prediction"]].head(10).to_string(index=False))

,Experiment,Exact Matches,Exact Accuracy (%),CER (%),WER (%),Mean Latency (ms),P50 Latency (ms),P99 Latency (ms),Empty Predictions
0,Original 200x31,11/48,22.92,46.48,77.08,31.98,29.88,59.61,18
1,Resized 800x124,3/48,6.25,58.80,93.75,52.06,47.27,178.74,22

Ground-truth formatting check:
ground_truth prediction
      1179.6     1179.6
     0018041     1804 1
     01441.8    1418kWh
      1927.7     1427.7
       672.7      672.7
      000001      0000O
      1025.0
      1320.5      13205
       01404
    002090.3   002090.3